server:
  port: 8888

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ENC(Y+6O4CIm8saxSdkU5Mc1asoAhTRn91s37uFt3HgKPBY5hBmWrx2iUjYq4oabRcms)
    username: ENC(g9NGIJXcf3q5rDmiH93Rmw==)
    password: ENC(mDfW/FGG98WTrCzz0d2qyQ==)
  jpa:
    generate-ddl: false
    show-sql: true
    database: mysql
    properties:
      hibernate:
        '[format_sql]': true
  data:
    redis:
      host: ENC(btnyrLqY+f7AO9+CMFNqh44Iz6WJMVST)
      port: 6379
      expiration_time: 259200000 #3일
  cache:
#    redis 캐시를 사용하기 위해 cache 타입을 redis로 설정
    type: redis

token:
  expiration_time: 86400000 #1일
#  secret: k/3f0rHITyFhkBQWfa7rlSAQ3s07wIgj7pUGgq5Q4EXbihvcPPapnHnKQAWV+u3mXJzIBQ9Cm++F0JPEHIv80g==
  secret: ENC(q9ML/EQLAdT+fVv5Qnj8gE/fU1lNBF6uQdeioxBCMKNoc2v7QkCD41002csydzvcf+iS89jMneK1SA/h/mvcNg4stuIqC/r++RODkaqhOWaNQ+y3z7EBGJ70+HHFugh9PEmR+S6kw4o=)

management:
  endpoints:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    web:
      exposure:
        include: health, info, metrics, prometheus
  metrics:
    tags:
      application: ${spring.application.name}

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
#    algorithm: PBEWithMD5AndDES
#    #    password: ${ENCRYPTION_PASSWORD:test}
#    iv-generator-classname: org.jasypt.iv.NoIvGenerator