apiVersion: apps/v1
kind: Deployment
metadata:
  name: itty-db-deployment
  labels:
    app: itty-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: itty-db
  template:
    metadata:
      labels:
        app: itty-db
    spec:
      containers:
      - name: itty-db
        image: eodud3196/db-server:latest # 여기에 실제 이미지 이름과 태그를 사용하세요.
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root" # 실제 사용할 루트 비밀번호로 변경하세요.
      volumes:
      - name: itty-db-pvc
        persistentVolumeClaim:
          claimName: itty-db-pvc